export const PHASES = {
  WELCOME: "welcome",
  SETUP: "setup",
  COMPOSE: "compose",
  TRAVELING: "traveling",
  CONTACT_DECISION: "contact_decision",
  DELETE_ATTEMPT: "delete_attempt",
  REVEAL: "reveal",
  DEBRIEF: "debrief",
  FINISHED: "finished",
};

export const MESSAGE_TYPES = [
  { id: "photo_mer", label: "Photo au bord de la mer", emoji: "🏖️", sensitivity: 1, hint: "Ça semble anodin... mais qui va la voir ?" },
  { id: "photo_soiree", label: "Photo de soirée entre amis", emoji: "🥳", sensitivity: 2, hint: "Tes amis sont-ils d'accord d'être sur la photo ?" },
  { id: "message_intime", label: "Message intime pour quelqu'un", emoji: "💌", sensitivity: 3, hint: "Très personnel. Attention au chemin que ça prend." },
  { id: "secret", label: "Un secret partagé entre amis", emoji: "🤫", sensitivity: 3, hint: "Un secret numérique n'en est plus vraiment un." },
  { id: "adresse_maison", label: "Mon adresse personnelle", emoji: "🏠", sensitivity: 3, hint: "Où tu vis. Qui doit vraiment le savoir ?" },
];

// Each step of the message's travel path
export const TRAVEL_STEPS = [
  {
    id: "depart",
    actor: "expediteur",
    emoji: "📱",
    title: "Tu appuies sur Envoyer",
    description: "Le message quitte ton appareil et entre dans le réseau.",
    copyHolder: null,
    copyLabel: null,
    bgColor: "#e8f5e9",
    bgColorDark: "#1a2e1c",
  },
  {
    id: "server1",
    actor: "server1",
    emoji: "🖥️",
    title: "Serveur 1 reçoit le message",
    description: "Le serveur crée automatiquement une copie de sauvegarde avant de transmettre. C'est technique, pas malveillant.",
    copyHolder: "server1",
    copyLabel: "Copie Serveur 1",
    bgColor: "#e3f2fd",
    bgColorDark: "#162132",
    badgeText: "📋 COPIE CRÉÉE",
    badgeColor: "#1565c0",
  },
  {
    id: "server2",
    actor: "server2",
    emoji: "🖥️",
    title: "Serveur 2 reçoit le message",
    description: "Un second serveur copie le message pour assurer la redondance. Tu n'en sais rien.",
    copyHolder: "server2",
    copyLabel: "Copie Serveur 2",
    bgColor: "#e3f2fd",
    bgColorDark: "#162132",
    badgeText: "📋 COPIE CRÉÉE",
    badgeColor: "#1565c0",
  },
  {
    id: "platform",
    actor: "plateforme",
    emoji: "🏢",
    title: "La Plateforme enregistre",
    description: "WhatsApp, Instagram, Snapchat... conservent une copie dans leurs serveurs. C'est écrit dans les CGU que personne ne lit.",
    copyHolder: "plateforme",
    copyLabel: "Archive Plateforme",
    bgColor: "#f3e5f5",
    bgColorDark: "#221528",
    badgeText: "💾 ARCHIVÉ",
    badgeColor: "#6a1b9a",
  },
  {
    id: "contact",
    actor: "contact",
    emoji: "👤",
    title: "Ton contact reçoit le message",
    description: "Le message est arrivé chez ton contact de confiance. Mais il a déjà fait 4 copies en chemin.",
    copyHolder: "contact",
    copyLabel: "Chez ton contact",
    bgColor: "#e8f5e9",
    bgColorDark: "#1a2e1c",
    badgeText: "✅ LIVRÉ",
    badgeColor: "#2e7d32",
  },
];

export const DEBRIEF_QUESTIONS = [
  {
    id: "surprise",
    question: "Expéditeur : tu t'attendais à autant de copies ?",
    icon: "😲",
    options: [
      { label: "Non, c'était surprenant !", value: "surprised" },
      { label: "J'en connaissais certaines", value: "partial" },
      { label: "Oui, je savais déjà", value: "knew" },
    ],
    lesson: "Chaque message numérique crée des copies automatiques à chaque étape de son trajet. C'est invisible, silencieux, mais bien réel.",
    lessonEmoji: "💡",
  },
  {
    id: "control",
    question: "Qui contrôle encore le message maintenant ?",
    icon: "🎮",
    options: [
      { label: "Personne vraiment", value: "nobody", correct: true },
      { label: "L'expéditeur", value: "sender" },
      { label: "La plateforme", value: "platform" },
    ],
    lesson: "Une fois envoyé, le message t'échappe complètement. La plateforme, les serveurs, et toute personne qui l'a reçu peut en faire ce qu'elle veut — même des années après.",
    lessonEmoji: "🔓",
  },
  {
    id: "wrongdoing",
    question: "Est-ce que quelqu'un a mal agi dans ce jeu ?",
    icon: "⚖️",
    options: [
      { label: "Le serveur qui a copié", value: "server" },
      { label: "Le contact qui a transféré", value: "contact" },
      { label: "Pas forcément — c'était automatique ou un choix", value: "nuanced", correct: true },
    ],
    lesson: "Les serveurs copient automatiquement — c'est du fonctionnement technique. Le contact a fait un choix humain. Les deux méritent réflexion, mais pour des raisons différentes.",
    lessonEmoji: "🧠",
  },
  {
    id: "intimate",
    question: "Et si le message contenait quelque chose d'intime ?",
    icon: "❤️",
    options: [
      { label: "Je ne l'aurais pas envoyé", value: "wouldnt_send" },
      { label: "J'aurais fait confiance à mon contact", value: "trusted" },
      { label: "Ça change tout — je vois le problème maintenant", value: "enlightened" },
    ],
    lesson: "Plus un message est sensible, plus il faut réfléchir avant d'appuyer sur Envoyer. Ce qui part ne peut pas vraiment être rappelé.",
    lessonEmoji: "🛡️",
  },
];
